import type { FlowRun } from './types'

export const mockWriteNextFlow: FlowRun = {
  id: 'write-next-success',
  title: '写下一场景',
  description: '从当前场景推导下一场景路径，读取故事记忆，构建 Prompt，调用 LLM，质量检查，保存结果，更新记忆',
  nodes: [
    {
      id: 'input-current-scene',
      label: '当前场景输入',
      description: '获取当前编辑的场景文件',
      type: 'input',
      status: 'success',
      outputs: [
        {
          id: 'current-file',
          label: 'sec-003.md',
          kind: 'file',
          path: 'chapters/vol-01/ch-001/sec-003.md',
          size: 2450,
          preview: '# 第1卷第1章第3场景\n\n林浩深吸一口气，向前迈出一步...\n\n（场景正文约1200字）',
          isMock: true,
        },
      ],
      durationMs: 12,
    },
    {
      id: 'derive-next-path',
      label: '推导下一场景路径',
      description: '根据当前场景位置，计算下一个要写的场景路径',
      type: 'process',
      status: 'success',
      inputs: [
        {
          id: 'input-path',
          label: 'sec-003.md',
          kind: 'file',
          path: 'chapters/vol-01/ch-001/sec-003.md',
          isMock: true,
        },
      ],
      outputs: [
        {
          id: 'target-path',
          label: 'sec-004.md',
          kind: 'file',
          path: 'chapters/vol-01/ch-001/sec-004.md',
          isMock: true,
        },
      ],
      durationMs: 8,
    },
    {
      id: 'load-memory',
      label: '读取故事记忆',
      description: '加载故事引擎、近期上下文和章节元数据',
      type: 'memory',
      status: 'success',
      inputs: [],
      outputs: [
        {
          id: 'story-engine',
          label: 'story-engine.md',
          kind: 'file',
          path: 'story-engine.md',
          size: 1250,
          preview: '# 故事引擎\n\n## 主角目标\n- 林浩：证明自己，摆脱羞辱，获得真正能改变命运的力量\n\n## 当前冲突\n- 旧秩序压迫，宗门试炼前的打压\n\n## 伏笔\n- 神秘玉佩的秘密\n- 林浩的真实身份',
          isMock: true,
        },
        {
          id: 'recent-context',
          label: 'recent-context.md',
          kind: 'file',
          path: 'recent-context.md',
          size: 820,
          preview: '# 近期上下文\n\n## 过去3个场景\n1. 林浩在宗门外广场受辱\n2. 神秘玉佩觉醒，带来异象\n3. 长老注意到林浩的变化\n\n## 人物状态\n- 林浩：愤怒、决心，实力初显',
          isMock: true,
        },
        {
          id: 'ch-meta',
          label: 'ch-meta.json',
          kind: 'json',
          path: 'chapters/vol-01/ch-001/ch-meta.json',
          size: 256,
          preview: '{\n  "chapter": 1,\n  "volume": 1,\n  "scenes_written": 3,\n  "total_scenes": 5,\n  "milestone_reached": false\n}',
          isMock: true,
        },
      ],
      durationMs: 45,
    },
    {
      id: 'build-prompt',
      label: '构建 Prompt',
      description: '组合故事记忆、用户偏好和当前场景，构建完整提示词',
      type: 'process',
      status: 'success',
      inputs: [
        {
          id: 'memory-input',
          label: '记忆数据',
          kind: 'json',
          isMock: true,
        },
        {
          id: 'prefs-input',
          label: '写作偏好',
          kind: 'json',
          preview: '{\n  "style": "热血",\n  "intensity": "标准",\n  "pace": "快节奏",\n  "protagonist": "张扬"\n}',
          isMock: true,
        },
        {
          id: 'current-content',
          label: '当前场景',
          kind: 'text',
          isMock: true,
        },
      ],
      outputs: [
        {
          id: 'final-prompt',
          label: 'Prompt',
          kind: 'prompt',
          preview: '# 任务：写第1卷第1章第4场景\n\n## 上下文\n当前场景：林浩在广场受辱后玉佩觉醒，引起注意\n\n## 故事引擎\n- 主角目标：证明自己\n- 当前冲突：旧秩序压迫\n\n## 写作偏好\n- 文风：热血\n- 节奏：快节奏\n- 爽点强度：标准\n\n## 要求\n1. 延续当前剧情\n2. 保持主角性格\n3. 800-1000字\n4. 设置下一个钩子',
          isMock: true,
        },
      ],
      durationMs: 23,
    },
    {
      id: 'call-llm',
      label: '调用 LLM',
      description: '向 AI 模型发送请求，生成场景内容',
      type: 'llm',
      status: 'success',
      inputs: [
        {
          id: 'prompt-input',
          label: 'Prompt',
          kind: 'prompt',
          isMock: true,
        },
      ],
      outputs: [
        {
          id: 'llm-output',
          label: '生成内容',
          kind: 'text',
          size: 3200,
          preview: '# 第1卷第1章第4场景\n\n林浩深吸一口气，手中长剑缓缓出鞘...\n\n他的目光扫过四周那些轻蔑的眼神，心中没有丝毫怯意，反而燃起熊熊斗志。\n\n"今日之辱，他日必当百倍奉还！"\n\n话音未落，林浩脚下步法展开，整个人如离弦之箭般冲向试炼台...\n\n（场景正文约850字）',
          isMock: true,
        },
      ],
      durationMs: 8762,
    },
    {
      id: 'quality-check',
      label: '质量检查',
      description: '检查生成内容的逻辑、爽点和连续性',
      type: 'quality',
      status: 'success',
      inputs: [
        {
          id: 'content-input',
          label: '生成内容',
          kind: 'text',
          isMock: true,
        },
      ],
      outputs: [
        {
          id: 'quality-result',
          label: '质量报告',
          kind: 'json',
          preview: '{\n  "score": 92,\n  "feedback": "逻辑通顺，爽点兑现，主角性格保持一致",\n  "issues": [],\n  "suggestions": []\n}',
          isMock: true,
        },
      ],
      durationMs: 1234,
    },
    {
      id: 'save-result',
      label: '保存结果',
      description: '将生成内容写入目标场景文件',
      type: 'file',
      status: 'success',
      inputs: [
        {
          id: 'final-content',
          label: '最终内容',
          kind: 'text',
          isMock: true,
        },
      ],
      outputs: [
        {
          id: 'saved-file',
          label: 'sec-004.md',
          kind: 'file',
          path: 'chapters/vol-01/ch-001/sec-004.md',
          size: 3250,
          isMock: true,
        },
      ],
      durationMs: 15,
    },
    {
      id: 'update-memory',
      label: '更新故事记忆',
      description: '更新故事引擎、近期上下文和章节元数据',
      type: 'memory',
      status: 'success',
      inputs: [
        {
          id: 'new-content',
          label: '新场景内容',
          kind: 'text',
          isMock: true,
        },
      ],
      outputs: [
        {
          id: 'updated-engine',
          label: 'story-engine.md',
          kind: 'file',
          path: 'story-engine.md',
          size: 1380,
          isMock: true,
        },
        {
          id: 'updated-meta',
          label: 'ch-meta.json',
          kind: 'json',
          path: 'chapters/vol-01/ch-001/ch-meta.json',
          preview: '{\n  "chapter": 1,\n  "volume": 1,\n  "scenes_written": 4,\n  "total_scenes": 5,\n  "milestone_reached": false\n}',
          isMock: true,
        },
      ],
      durationMs: 38,
    },
    {
      id: 'refresh-ui',
      label: '刷新编辑器',
      description: '更新编辑器显示，准备下一场景选项',
      type: 'ui',
      status: 'success',
      durationMs: 42,
    },
  ],
}

export const mockErrorFlow: FlowRun = {
  id: 'write-next-error',
  title: '写下一场景（失败示例）',
  description: '模拟 LLM 请求超时的失败流程',
  nodes: [
    {
      id: 'input-current-scene',
      label: '当前场景输入',
      description: '获取当前编辑的场景文件',
      type: 'input',
      status: 'success',
      outputs: [
        {
          id: 'current-file',
          label: 'sec-003.md',
          kind: 'file',
          path: 'chapters/vol-01/ch-001/sec-003.md',
          size: 2450,
          isMock: true,
        },
      ],
      durationMs: 12,
    },
    {
      id: 'derive-next-path',
      label: '推导下一场景路径',
      description: '根据当前场景位置，计算下一个要写的场景路径',
      type: 'process',
      status: 'success',
      inputs: [
        {
          id: 'input-path',
          label: 'sec-003.md',
          kind: 'file',
          path: 'chapters/vol-01/ch-001/sec-003.md',
          isMock: true,
        },
      ],
      outputs: [
        {
          id: 'target-path',
          label: 'sec-004.md',
          kind: 'file',
          path: 'chapters/vol-01/ch-001/sec-004.md',
          isMock: true,
        },
      ],
      durationMs: 8,
    },
    {
      id: 'load-memory',
      label: '读取故事记忆',
      description: '加载故事引擎、近期上下文和章节元数据',
      type: 'memory',
      status: 'success',
      outputs: [
        {
          id: 'story-engine',
          label: 'story-engine.md',
          kind: 'file',
          path: 'story-engine.md',
          isMock: true,
        },
      ],
      durationMs: 45,
    },
    {
      id: 'build-prompt',
      label: '构建 Prompt',
      description: '组合故事记忆、用户偏好和当前场景',
      type: 'process',
      status: 'success',
      outputs: [
        {
          id: 'final-prompt',
          label: 'Prompt',
          kind: 'prompt',
          isMock: true,
        },
      ],
      durationMs: 23,
    },
    {
      id: 'call-llm',
      label: '调用 LLM',
      description: '向 AI 模型发送请求，生成场景内容',
      type: 'llm',
      status: 'error',
      error: 'LLM timeout after 45s',
      inputs: [
        {
          id: 'prompt-input',
          label: 'Prompt',
          kind: 'prompt',
          isMock: true,
        },
      ],
      durationMs: 45000,
    },
    {
      id: 'quality-check',
      label: '质量检查',
      description: '检查生成内容的逻辑、爽点和连续性（因上游失败跳过）',
      type: 'quality',
      status: 'skipped',
    },
    {
      id: 'save-result',
      label: '保存结果',
      description: '将生成内容写入目标场景文件（因上游失败跳过）',
      type: 'file',
      status: 'skipped',
    },
    {
      id: 'update-memory',
      label: '更新故事记忆',
      description: '更新故事引擎和章节元数据（因上游失败跳过）',
      type: 'memory',
      status: 'skipped',
    },
    {
      id: 'refresh-ui',
      label: '刷新编辑器',
      description: '更新编辑器显示（因上游失败跳过）',
      type: 'ui',
      status: 'skipped',
    },
  ],
}
